name: Deploy to Server

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 环境

    steps:
      # Checkout 仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 SSH 密钥，连接到服务器
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}  # 使用 GitHub Secrets 存储私钥

      # 安装依赖并构建应用
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 上传构建产物到服务器
      - name: Upload build artifacts to server
        run: |
          scp -o StrictHostKeyChecking=no -r ./* MetaVibe@34.139.90.125:/home/MetaVibe/temp

      # 复制代码到服务器并执行命令
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no MetaVibe@34.139.90.125 "sudo systemctl status faithtime-nextjs"
